# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 01:02
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postphoto',
            name='height',
        ),
        migrations.RemoveField(
            model_name='postphoto',
            name='width',
        ),
        migrations.AlterField(
            model_name='postphoto',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='blog/post_pics'),
        ),
    ]
