# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 02:26
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170718_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='blog/post_pics'),
        ),
    ]
