# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 02:35
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170720_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
